# Generated by Django 6.0.2 on 2026-02-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
