# Generated by Django 6.0.2 on 2026-02-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('num_pages', models.IntegerField(blank=True, default=0, null=True)),
                ('average_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('published_year', models.CharField(blank=True, max_length=4, null=True)),
                ('available_copies', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'books_books',
            },
        ),
    ]
